# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-11 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NNGModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255, null=True, verbose_name='краткий адрес')),
                ('full_address', models.CharField(default='', max_length=255, null=True, verbose_name='полный адрес адрес')),
                ('email', models.CharField(default='', max_length=255, null=True, verbose_name='email')),
                ('telefons', models.CharField(default='', max_length=255, null=True, verbose_name='телефоны через запятую')),
                ('text_context', models.CharField(default='', max_length=255, null=True, verbose_name='заголовок')),
                ('context_context', models.CharField(default='', max_length=255, null=True, verbose_name='лозунг')),
                ('company', models.TextField(default='', null=True, verbose_name='текст о компании')),
                ('geografy', models.TextField(default='', null=True, verbose_name='текст о географии услуг')),
                ('vkansii', models.TextField(default='', null=True, verbose_name='текст о вакансии')),
                ('opit_zagolok', models.TextField(default='', null=True, verbose_name='Опыт заголовок')),
                ('opit_text', models.TextField(default='', null=True, verbose_name='текст об опыте')),
            ],
        ),
    ]
