# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nngconsulting', '0002_practici'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practici',
            options={'verbose_name': 'Описание практик'},
        ),
        migrations.AlterField(
            model_name='practici',
            name='name',
            field=models.TextField(default='', null=True, verbose_name='текст о компании'),
        ),
        migrations.AlterField(
            model_name='practici',
            name='note',
            field=models.TextField(default='', null=True, verbose_name='текст о компании'),
        ),
    ]
